In [1]:
# Find the square root of all elements.
# arr = np.array([4, 16, 36, 49])
import numpy as np
arr = np.array([4, 16, 36, 49])
print(np.sqrt(arr))

[2. 4. 6. 7.]


In [2]:
# Calculate the exponential (e^x) of each element.
# arr = np.array([0, 1, 2])
import numpy as np
arr = np.array([0, 1, 2])
print(np.exp(arr))

[1.         2.71828183 7.3890561 ]


In [3]:
# Compute the natural log of each element.
# arr = np.array([1, np.e, np.e**2])
import numpy as np
arr = np.array([1, np.e, np.e**2])
print(np.log(arr))

[0. 1. 2.]


In [4]:
# Find the sine of each angle in the array.
# angles = np.array([0, np.pi/2, np.pi])
import numpy as np
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [5]:
# Label each value as "High" if greater than 50, otherwise "Low".
# data = np.array([45, 51, 39, 62, 25])
import numpy as np
data = np.array([45, 51, 39, 62, 25])
result = np.where(data > 50, "High", "Low")
print(result)

['Low' 'High' 'Low' 'High' 'Low']


In [6]:
# Return only the unique values from the array.
# arr = np.array([1, 2, 2, 3, 3, 3, 4])
import numpy as np
arr = np.array([1, 2, 2, 3, 3, 3, 4])
print(np.unique(arr))

[1 2 3 4]


In [7]:
# Sort this 1D array.
# arr = np.array([8, 3, 1, 5])
import numpy as np
arr = np.array([8, 3, 1, 5])
print(np.sort(arr))

[1 3 5 8]


In [8]:
# Sort each row of the following 2D array.
# arr = np.array([[3, 1, 2], [9, 7, 8]])
import numpy as np
arr = np.array([[3, 1, 2], [9, 7, 8]])
print(np.sort(arr))

[[1 2 3]
 [7 8 9]]


In [9]:
 # Find the cosine values of the given angles.
# angles = np.array([0, np.pi/3, np.pi/2])
import numpy as np
angles = np.array([0, np.pi/3, np.pi/2])
print(np.cos(angles))

[1.000000e+00 5.000000e-01 6.123234e-17]


In [10]:
# Label all elements divisible by 3 as "Div3", otherwise "NotDiv3".
# arr = np.array([9, 12, 15, 22, 25, 30])
import numpy as np
arr = np.array([9, 12, 15, 22, 25, 30])
div_by_3 = np.where(arr % 3 == 0, "Div3", "NotDiv3")
print(div_by_3)

['Div3' 'Div3' 'Div3' 'NotDiv3' 'NotDiv3' 'Div3']


In [11]:
# Sort each row of the matrix.
# matrix = np.array([[11, 5, 9],
#                    [3, 8, 6]])
import numpy as np
matrix = np.array([[11, 5, 9],
                   [3, 8, 6]])
print(np.sort(matrix))

[[ 5  9 11]
 [ 3  6  8]]


In [12]:
# Compute exponential of each element, then take log of the result.
# arr = np.array([1, 2, 3, 4])
import numpy as np
arr = np.array([1, 2, 3, 4])
result = np.exp(arr)
print(result)
log = np.log(result)
print(log)

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1. 2. 3. 4.]


In [13]:
# Return unique values and their counts.
# arr = np.array([1, 1, 2, 3, 3, 3])
import numpy as np
arr = np.array([1, 1, 2, 3, 3, 3])
unq, counts = np.unique(arr, return_counts = True)
print(unq)
print(counts)

[1 2 3]
[2 1 3]


In [14]:
# Find unique elements and how many times each appeared.
# arr = np.array([2, 4, 4, 4, 6, 2, 8])
import numpy as np
arr = np.array([2, 4, 4, 4, 6, 2, 8])
unq, counts = np.unique(arr, return_counts = True)
print(unq)
print(counts)

[2 4 6 8]
[2 3 1 1]


In [15]:
# Replace all even numbers in the array with 0.
# arr = np.array([1, 2, 3, 4, 5, 6])
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.where(arr % 2 == 0, 0, arr)
print(result)

[1 0 3 0 5 0]


In [16]:
# Check sin²(x) + cos²(x) ≈ 1 for each angle.
# x = np.array([0, np.pi/4, np.pi/2])
import numpy as np
x = np.array([0, np.pi/4, np.pi/2])
result = np.sin(x)**2 + np.cos(x)**2
check = np.isclose(result, 1.0)
print(check)

[ True  True  True]
